name: Build on push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Read version
        id: version
        run: echo "APP_VERSION=${python version.py get}" >> $GITHUB_ENV

      - name: Run build script
        run: |
          python build.py

      - name: Unzip build results
        run: |
          mkdir extracted
          powershell -Command "Expand-Archive -Path dist/BfMUI_desktop.zip -DestinationPath extracted"

      - name: Upload artifact - desktop
        uses: actions/upload-artifact@v4
        with:
          name: BfMUI_desktop_dist-${{ env.APP_VERSION }}
          path: extracted/
      
      - name: Upload artifact - android
        uses: actions/upload-artifact@v4
        with:
          name: BfMUI_android_dist-${{ env.APP_VERSION }}
          path: apk/bfmui.apk
